import { SentimentScores } from '../types';

/**
 * Pre-scored sentiment for all 51 influencers from tweet analysis.
 * Generated by scripts/applyScoresToReact.js on 2026-04-29.
 */
export const sentimentScores: Record<string, SentimentScores> = {
  addyosmani        : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  alexandr_wang     : { trends: 'optimistic', regulation: 0.50, usage: 1.00, trust: 0.70, agent: 1.00 },  // tweets
  andrewyng         : { trends: 'optimistic', regulation: -1.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  arankomatsuzaki   : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: -0.50, agent: 0.50 },  // tweets
  aelluswamy        : { trends: 'optimistic', regulation: 0.50, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  austen            : { trends: 'optimistic', regulation: -0.80, usage: 1.00, trust: 0.80, agent: 0.30 },  // tweets
  chrmanning        : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 0.50, agent: -0.50 },  // tweets
  clementdelangue   : { trends: 'optimistic', regulation: 0.50, usage: 1.00, trust: 0.80, agent: 0.70 },  // web-search
  darioamodei       : { trends: 'neutral', regulation: 1.00, usage: 0.75, trust: -0.80, agent: 0.70 },  // web-search
  deryatr_          : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  esyudkowsky       : { trends: 'pessimistic', regulation: 1.00, usage: -1.00, trust: -1.00, agent: -1.00 },  // tweets
  emostaque         : { trends: 'optimistic', regulation: 0.80, usage: 1.00, trust: -1.00, agent: 1.00 },  // tweets
  gavinsbaker       : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  goodfellow_ian    : { trends: 'optimistic', regulation: 1.00, usage: 1.00, trust: 0.50, agent: 0.00 },  // tweets
  jeffdean          : { trends: 'optimistic', regulation: -0.50, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  drjimfan          : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: -0.50, agent: 0.80 },  // tweets
  schmidhuberai     : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  kazu_fujisawa     : { trends: 'pessimistic', regulation: 0.00, usage: 0.00, trust: -1.00, agent: 0.00 },  // tweets
  minchoi           : { trends: 'optimistic', regulation: -0.20, usage: 1.00, trust: -0.40, agent: 0.60 },  // tweets
  miramurati        : { trends: 'optimistic', regulation: 1.00, usage: 1.00, trust: 0.70, agent: 0.70 },  // tweets
  mitchellh         : { trends: 'optimistic', regulation: 1.00, usage: 1.00, trust: -1.00, agent: 1.00 },  // tweets
  officiallogank    : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  oriolvinyalsml    : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  palmerluckey      : { trends: 'optimistic', regulation: -0.90, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  goodside          : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: -0.50, agent: 0.00 },  // tweets
  rasbt             : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 0.50, agent: 1.00 },  // tweets
  _akhaliq          : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  fchollet          : { trends: 'neutral', regulation: 0.70, usage: 0.80, trust: -0.50, agent: 0.90 },  // tweets
  ilyasut           : { trends: 'optimistic', regulation: 0.50, usage: 1.00, trust: -1.00, agent: 0.00 },  // tweets
  drfeifei          : { trends: 'optimistic', regulation: 0.50, usage: 1.00, trust: 0.50, agent: 1.00 },  // tweets
  geoffreyhinton    : { trends: 'pessimistic', regulation: 1.00, usage: 0.50, trust: -1.00, agent: -1.00 },  // tweets
  paraga            : { trends: 'optimistic', regulation: 0.50, usage: 1.00, trust: 0.70, agent: 1.00 },  // mixed
  bcherny           : { trends: 'optimistic', regulation: 0.70, usage: 1.00, trust: 0.80, agent: 1.00 },  // tweets
  brian_armstrong   : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  demishassabis     : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  elonmusk          : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  gdb               : { trends: 'optimistic', regulation: 0.50, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  hardmaru          : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  jeremyphoward     : { trends: 'optimistic', regulation: -1.00, usage: 1.00, trust: -0.50, agent: 0.75 },  // tweets
  yacinemtb         : { trends: 'optimistic', regulation: -1.00, usage: 1.00, trust: 0.75, agent: 1.00 },  // tweets
  karpathy          : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  levie             : { trends: 'optimistic', regulation: 0.80, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  mustafasuleyman   : { trends: 'optimistic', regulation: 1.00, usage: 1.00, trust: -1.00, agent: 1.00 },  // tweets
  omarsar0          : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 0.50, agent: 1.00 },  // tweets
  sama              : { trends: 'optimistic', regulation: 0.50, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  satyanadella      : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  soumithchintala   : { trends: 'optimistic', regulation: 0.00, usage: 1.00, trust: 0.75, agent: 1.00 },  // tweets
  sriramk           : { trends: 'optimistic', regulation: -0.50, usage: 1.00, trust: 1.00, agent: 1.00 },  // tweets
  steipete          : { trends: 'optimistic', regulation: 0.50, usage: 1.00, trust: -0.50, agent: 1.00 },  // tweets
  tunguz            : { trends: 'optimistic', regulation: -0.50, usage: 1.00, trust: 0.75, agent: 0.00 },  // tweets
  ylecun            : { trends: 'optimistic', regulation: -0.50, usage: 0.70, trust: 0.80, agent: 0.90 },  // web-search
};
