/**
 * applyScoresToReact.js
 *
 * Reads scripts/sentimentOutput.json and writes data/sentimentScores.ts
 * so the React app uses the pre-scored tweet-derived sentiment data.
 *
 * Usage:
 *   node scripts/applyScoresToReact.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname  = path.dirname(fileURLToPath(import.meta.url));
const INPUT      = path.join(__dirname, 'sentimentOutput.json');
const OUTPUT     = path.join(__dirname, '..', 'data', 'sentimentScores.ts');

if (!fs.existsSync(INPUT)) {
  console.error('sentimentOutput.json not found — run scoreSentiment.js first');
  process.exit(1);
}

const scores = JSON.parse(fs.readFileSync(INPUT, 'utf8'));

const clamp = v => Math.max(-1, Math.min(1, Number(v) || 0));
const validTrends = ['optimistic', 'pessimistic', 'neutral', 'cautious'];

const lines = [];
lines.push(`import { SentimentScores } from '../types';`);
lines.push('');
lines.push('/**');
lines.push(' * Pre-scored sentiment for all 51 influencers from tweet analysis.');
lines.push(` * Generated by scripts/applyScoresToReact.js on ${new Date().toISOString().slice(0, 10)}.`);
lines.push(' */');
lines.push('export const sentimentScores: Record<string, SentimentScores> = {');

let count = 0;
for (const [id, result] of Object.entries(scores)) {
  if (!result || !result.sentiment) continue;
  const s = result.sentiment;
  const trends = validTrends.includes(s.trends) ? s.trends : 'neutral';
  const reg = clamp(s.regulation).toFixed(2);
  const use = clamp(s.usage).toFixed(2);
  const tru = clamp(s.trust).toFixed(2);
  const age = clamp(s.agent).toFixed(2);
  const src = s.source ? `  // ${s.source}` : '';
  lines.push(`  ${id.padEnd(18)}: { trends: '${trends}', regulation: ${reg}, usage: ${use}, trust: ${tru}, agent: ${age} },${src}`);
  count++;
}

lines.push('};');
lines.push('');

fs.writeFileSync(OUTPUT, lines.join('\n'));
console.log(`✓ Wrote ${count} scores to data/sentimentScores.ts`);
